### ISSUE TITLE
can't jump to calibre window

### ISSUE THREAD

**Issue by tpapp** [mkropat/jumpapp#16]
[Calibre](https://calibre-ebook.com/) is an e-book manager/reader.

``` bash
$ wmctrl -l
0x01400004 -1 tamas xfce4-panel
0x01a00003 -1 tamas Desktop
0x01e0009b  0 tamas emacs@tamas
0x03400004  0 tamas Terminal
0x05000013  0 tamas Okular
0x04800004  0   N/A calibre - || research ||
$ jumpapp calibre
Error: found running process for 'calibre', but found no window to jump to
```

but

``` bash
wmctrl -a calibre
```

works fine.

Using jumpapp 0.8-1 (Debian), compiled from git repo.

**Comment by mkropat** [comment]
Thanks for the bug report. Can you post a comment with the output of `jumapp -L calibre`?

I'll try looking into it sometime this week when I find a little free time. I'm curious to try and see if it's a new issue in 0.8 or whether it's always been there.

**Comment by tpapp** [comment]
```sh
$ jumpapp -L calibre
Matched Windows [0]
```
The issue was the same before 0.8, but I have been using jumpapp for 3 days only, and when I saw the update I thought I would install the new version before reporting a bug.

**Comment by mkropat** [comment]
This appears to be working for me when I tried it just now:

```
$ jumpapp -L calibre
Matched Windows [1]
0x05c0000f N/A 5254 0 calibre: calibre - || Calibre Library ||
```

I'm not sure if something changed in jumpapp, or Calibre, or maybe it it is machine dependent, but I'm going to close this issue for now.

If anyone is running into this issue, feel free to re-open this issue or create a new one. Thanks.
