### ISSUE TITLE
What to do if the window is not found ( Telegram / PyCharm related )

### ISSUE THREAD

**Issue by benzkji** [mkropat/jumpapp#20]
I use jumpapp as my main window switcher, it works great (THANK YOU)! Besides two exceptions, that are Telegram and PyCharm. Both not installed via package manager, they are a bit different, it seems.

I tried `jumpapp ~Apps/Telegram/Telegram` (downloaded a binary), and also `jumpapp ~Apps/Telegram/Telegram -i/c/t "Telegram"` (the window title obviously is "Telegram"), but always get a `Error: found running process for 'Telegram', but found no window to jump to`. Same for PyCharm, this is a java app though.

Any directions very appreciated.

(I'm under xfce/xubuntu 16.10, if that matters?)

**Comment by rgtk** [comment]
Use `jumpapp -f $TELEGRAM_EXEC TelegramDesktop`.
For me `$TELEGRAM_EXEC` is `/opt/Telegram/Telegram`, for you it should be `~/Apps/Telegram/Telegram`.

The reason that your command didn't work is that Telegram has `Telegram` binary but its window class name is `TelegramDesktop`. 

You can see X properties of selected window (including class name which is used by jumpapp to determine proper window) by executing `xprop -id $(xdotool selectwindow)` and clicking on target.

**Comment by benzkji** [comment]
Thank you. That xprop thing is quite helpful!

Reading --help again, I noted that OPTIONS should come before COMMAND...so, now, for me, this works:

    jumpapp -c TelegramDesktop ~/Apps/Telegram/Telegram 

Launches and switches to Telegram, so works perfectly.

**Comment by mkropat** [comment]
Glad you got it figured out. Thanks @rgtk, I love it when jumpapp users are able to help each other.

It's definitely a little annoying that OPTIONS have to come before the COMMAND. It's a limitation of bash's `getopts` functionality, that'd have to be worked around to fix, which may be more trouble than it's worth.
