### ISSUE TITLE
found running process for 'gnome-terminal', but found no window to jump to

### ISSUE THREAD

**Issue by der-Daniel** [mkropat/jumpapp#28]
Hi,

I am using Arch with Gnome.
When I try to execute `jumpapp gnome-terminal` I get the error `found running process for 'gnome-terminal', but found no window to jump to`.

Any idea why this is the case. `wmctrl -l` also does not include gnome-terminal..

For Frodo.

**Comment by e3rd** [comment]
And what does it include please?  
(If nothing works you may want eventually IE set a default title for gnome-terminal a jumpapp with title flag -t.)

**Comment by der-Daniel** [comment]
At this moment:

    0x02400001  0 diego Rambox - WhatsApp
    0x02000010  0 diego found running process for 'gnome-terminal', but found no window to jump to · Issue #28 · mkropat/jumpapp - Mozilla Firefox

**Comment by e3rd** [comment]
As I have Ubuntu, I can hardly test your environment :(
Anyone else with Arch here?
Good luck

**Comment by der-Daniel** [comment]
Here are some more information.
I just lightdm on arch and recently switched to gdm.
I just tried it with lightdm again and everything works as expected.
Has this to do with wayland or other things?

**Comment by der-Daniel** [comment]
I found the issue.
gdm has loaded Wayland by default, whereas light has loaded Xorg.
Using Xorg in gdm solved the issue.

**Comment by Gr-Fr** [comment]
I have the same problem with terminal and firefox
and yes, using Xorg in gdm solved the issue
but then another problem arises, at 4k resolution, the ubuntu interface starts to slow down
if there is another way to solve the problem?
I can assume that I can find an alternative terminal, but what to do with firefox (unfortunately, I need to use firefox)
