### ISSUE TITLE
jumpapp + alias commandName = " Unable to find command 'commandName' "

### ISSUE THREAD

**Issue by BrianD91** [mkropat/jumpapp#37]
I'm trying to use jumpapp as a way to open vscodium ( a FLOSS fork for VSCode ).

Running Kubuntu 18.04

I've created an alias in my .bashrc ` alias vscodium='~/Programs/vscodium' `

When I type the vscodium alias into a terminal window, it launches the program. However; when I type 'jumpapp vscodium' into the terminal I am greeted with `Error: Unable to find command 'vscodium'`

BUT, if I type the vscodium command by itself, and get the application up and running, and THEN type 'jumpapp vscodium' into the terminal, the jumpapp will work as expected, bringing VSCodium to the front.

**Comment by BrianD91** [comment]
Closed, I was able to resolve this by using the -t flag and fallback path to the program I'm trying to open.

**Comment by mkropat** [comment]
Glad you got it to work. That's what `-t` is there for. Another option might be to add `vscodium` to the `$PATH`.
