### ISSUE TITLE
Error: found running process for 'Telegram', but found no window to jump to

### ISSUE THREAD

**Issue by goldylucks** [mkropat/jumpapp#44]
This program is AMAZING, you ROCK man!

Here's the bug I encountered:

```bash
$ jumpapp Telegram
Launching: Telegram 
# switch focus back to terminal
$ jumpapp Telegram
Error: found running process for 'Telegram', but found no window to jump to
```

this happens on Telegram, but not on spotify:
![image](https://user-images.githubusercontent.com/6963212/59961426-59b30380-94e0-11e9-830b-98204ad79b7b.png)

Things tried:
```bash
$ jumpapp Telegram       
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -t Telegram
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -t=Telegram
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -c=Telegram
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -c Telegram
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -i Telegram
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -i=Telegram
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -C         
Error: found running process for 'Telegram', but found no window to jump to

```

Both telegram and whatsapp are on my dock:
![image](https://user-images.githubusercontent.com/6963212/59961483-f1185680-94e0-11e9-9ab5-b635e7dca395.png)

And Telegram is in my path.

Anything I can do to help debug this?

Thanks!

**Comment by goldylucks** [comment]
Also ran this:
```bash
$ wmctrl -l -x                
0x01a00004  0 Telegram.TelegramDesktop    N/A Telegram
0x02200001  0 spotify.Spotify       goldy Spotify Premium
```

Note that spotify is on my user (goldy) and Telegram is N/A.

I then tried these with no luck:
```bash
remove audacity

$ jumpapp Telegram -t Telegram.TelegramDesktop
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -c Telegram.TelegramDesktop
Error: found running process for 'Telegram', but found no window to jump to
$ jumpapp Telegram -i Telegram.TelegramDesktop
Error: found running process for 'Telegram', but found no window to jump to



```

**Comment by goldylucks** [comment]
I tried installing telegram with `snap`. Now it doesn't throw an error, but also it doesn't jump to telegram.

![Peek 2019-06-22 12-00](https://user-images.githubusercontent.com/6963212/59961807-5b32fa80-94e5-11e9-8637-661ea5b80dc1.gif)

**Comment by goldylucks** [comment]
Tried the same on single screen, same result :(

**Comment by goldylucks** [comment]
So, after installing the gnome extension [focus my window](https://extensions.gnome.org/extension/1005/focus-my-window/) jumpapp works flawlessly with everything!

I'm closing this.

I think it will be a good idea to mention that in the docs/readme :)

**Comment by mkropat** [comment]
Thanks for the bug report!

It looks like the issue with Telegram is that it doesn't set its hostname on the window:

```
$ xprop -name Telegram WM_CLIENT_MACHINE
WM_CLIENT_MACHINE:  not found.
```

jumpapp looks at the hostname before performing a PID match so that it doesn't inadvertently match a window running on another host that happens to have the same PID.

However, if the hostname is missing, why not have jumpapp try to do a PID match anyway? I made the change in #45.

If you pull down the latest code, Telegram should work now.

**Comment by goldylucks** [comment]
sweet thanks!

**Comment by jimh69** [comment]
I am having a similar issue.  Jumpapp is indeed opening an app (terminal, browser, etc.) initially, but won't jump to it.  It doesn't matter if the app is in the same window or in another workspace.  

Manually calling it from a terminal gives results like this:
`Error: found running process for 'nautilus', but found no window to jump to`

I'm running Gnome in NixOS.  Very new system with few other apps and most defaults still in place.

What's tragic is I had this working _perfectly_ on a previous installation.  Wiped that (for unrelated reasons) thinking just setting up hotkeys after a jumpapp install was all I needed.  Obviously I missed something (a basic setting or some extension) and it's maddening.
