### ISSUE TITLE
AUR package is no longer maintained

### ISSUE THREAD

**Issue by maxigaz** [mkropat/jumpapp#50]
I’ve just noticed that the AUR package [`jumpapp-git`](https://aur.archlinux.org/packages/jumpapp-git) doesn’t have a maintainer any more, and currently there are no other packages for Arch Linux and Arch-based distros.

**Comment by maxigaz** [comment]
Update: It now has a maintainer. Kudos!

**Comment by mkropat** [comment]
Nice. Thanks @maxigaz for reporting this! Glad it's all worked out.
