### ISSUE TITLE
Can't jump to visual-studio-code-insiders

### ISSUE THREAD

**Issue by escape0707** [mkropat/jumpapp#51]
First, huge thanks to making this awesome tool! I use it to jump accross firefox and vscode swiftly. It's cool!

But recently I decided to go for a trial with vscode-insiders. On ArchLinux.

I invoked `jumpapp code-insiders`, it run `code-insiders` for me.
Then I invoke the same command again, it says:

```shell
Error: found running process for 'code-insiders', but found no window to jump to
```

<details>
<summary>I tried: `xprop -id $(xdotool selectwindow)` and got: <br><strong>(PLEASE CLICK TO EXPAND)</strong></summary>

```shell
$ xprop -id $(xdotool selectwindow)
_NET_WM_ICON_GEOMETRY(CARDINAL) = 506, 0, 200, 26
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0xa66e3200
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT
_NET_WM_USER_TIME(CARDINAL) = 10062885
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 27
		program specified minimum size: 600 by 270
_NET_WM_ICON(CARDINAL) = 
WM_NAME(UTF8_STRING) = "test.py - my_project - Visual Studio Code - Insiders"
_NET_WM_NAME(UTF8_STRING) = "test.py - my_project - Visual Studio Code - Insiders"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 56623106, 56623107
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "code - insiders", "Code - Insiders"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 17019
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "MyLaptop"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```
</details>

Then I tried `-C` option:
```shell
$ jumpapp -C code\ -\ insiders code-insiders
Error: unable to find command 'code - insiders'
$ jumpapp -C Code\ -\ Insiders code-insiders
Error: unable to find command 'Code - Insiders'
```

Sadly they don't work.

Here is what `wmctrl -lx` gives:
```shell
$ wmctrl -lx
0x00c00003 -1 xfce4-panel.Xfce4-panel  MyLaptop xfce4-panel
0x00c0000d -1 xfce4-panel.Xfce4-panel  MyLaptop xfce4-panel
0x00c00011 -1 xfce4-panel.Xfce4-panel  MyLaptop xfce4-panel
0x01000028 -1 xfdesktop.Xfdesktop   MyLaptop Desktop
0x04000003  0 Navigator.Nightly     MyLaptop New Issue · mkropat/jumpapp - Firefox Nightly
0x04e0000c  0 xfce4-taskmanager.Xfce4-taskmanager  MyLaptop Task Manager
0x05400003  0 xfce4-terminal.Xfce4-terminal  MyLaptop Terminal - me@MyLaptop:~
0x03600001  0 code - insiders.Code - Insiders  MyLaptop test.py - my_project - Visual Studio Code - Insiders
```

What can I do next?

**Comment by dotiful** [comment]
I have the same problem, waiting for a solution

**Comment by Rublis** [comment]
You could try to use:
`jumpapp -C -c insiders.Code code-insiders`
or:
`jumpapp -C -c Insiders code-insiders`

**Comment by escape0707** [comment]
Still no luck:

```sh
$ jumpapp -C -c insiders.Code code-insiders
Error: found running process for 'code-insiders', but found no window to
jump to
$ jumpapp -C -c Insiders code-insiders
Error: found running process for 'code-insiders', but found no window to
jump to
$ jumpapp -C insiders.Code code-insiders
Error: unable to find command 'insiders.Code'
$ jumpapp -C Insiders code-insiders
Error: unable to find command 'Insiders'
```

**Comment by escape0707** [comment]
> You could try to use:
> `jumpapp -C -c insiders.Code code-insiders`
> or:
> `jumpapp -C -c Insiders code-insiders`
> and see if that helps!?
> 
> P.S:
> That `-C` (upper C) is used for centring mouse cursor to the middle of opening windows. So You should use lower c instead:
> 
> ```
>   -r -- cycle through windows in reverse order
>   -f -- force COMMAND to launch if process found but no windows found
>   -m -- if a single window is already open and in focus - minimize it
>   -n -- do not fork into background when launching COMMAND
>   -p -- always launch COMMAND when ARGs passed
>         (see Argument Passthrough in man page)
>   -L -- list matching windows for COMMAND and quit
>   -t NAME -- process window has to have NAME as the window title
>   -c NAME -- find window using NAME as WM_CLASS (instead of COMMAND)
>   -i NAME -- find process using NAME as the command name (instead of COMMAND)
>   -w -- only find the applications in the current workspace
>   -R -- bring the application to the current workspace when raising
>         (the default behaviour is to switch to the workspace that the
>         application is currently on)
>   -C -- center cursor when raising application
> ```

Still no luck:

```sh
$ jumpapp -C -c insiders.Code code-insiders
Error: found running process for 'code-insiders', but found no window to
jump to
$ jumpapp -C -c Insiders code-insiders
Error: found running process for 'code-insiders', but found no window to
jump to
$ jumpapp -C insiders.Code code-insiders
Error: unable to find command 'insiders.Code'
$ jumpapp -C Insiders code-insiders
Error: unable to find command 'Insiders'
```

**Comment by Rublis** [comment]
Ok, goona install code insider and check if I can help with that

**Comment by Rublis** [comment]
The problem is that code insider uses WM_NAME with space in it. And jumppapp splits wmctrl output by spaces. Currently You should be able to use simply like this:
`jumpapp -C -c code code-insiders`

**Comment by escape0707** [comment]
Thanks for your help! Gonna check it out when I'm home.

**Comment by escape0707** [comment]
> The problem is that code insider uses WM_NAME with space in it. And jumppapp splits wmctrl output by spaces. Currently You should be able to use simply like this:
> `jumpapp -C -c code code-insiders`

Thanks! It works perfectly! I'm closing this issue now.

**Comment by myrdd** [comment]
I created PR #87 which fixes the issue. :)
