### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by vstepaniuk** [mkropat/jumpapp#56]
Need to add `git` to install if you do `git clone` later.

**Comment by gitressa** [comment]
I have added git in this PR: #57.

**Comment by gitressa** [comment]
The Merge Request #57 has been accepted, so this issue can be closed.

**Comment by mkropat** [comment]
Thank you for your work @gitressa !

**Comment by gitressa** [comment]
You're welcome @mkropat, thanks for making and maintaining `jumpapp`! The functionality (or program) ought to be included in Ubuntu by default.
