### ISSUE TITLE
Super button with xbindkeys?

### ISSUE THREAD

**Issue by gitressa** [mkropat/jumpapp#60]
Has anyone managed to get the Super key (a.k.a. Windows key) working with [xbindkeys](https://github.com/mkropat/jumpapp#xbindkeys)? This works fine in `.xbindkeysrc`:
```
"jumpapp firefox"
  control + alt + f
```
I am trying with this, but nothing happens:
```
"jumpapp firefox"
  super + alt + f
```

OS: Ubuntu 20.04.1

**Comment by e3rd** [comment]
I am not using `xbindkeys` right now but it the past versions of Ubuntu, `Mod2` worked for me.

Ex: `Shift+Mod2+Mod4 + KP_9` = Shift + with Num lock on + Super + keypad 9

`xmodmap` helped me

```bash
$ xmodmap
xmodmap:  up to 3 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        ISO_Next_Group (0x5e)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3        ISO_Level5_Shift (0xcb)
mod4        Super_L (0x85),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c)
```

**Comment by gitressa** [comment]
Thanks @e3rd, that was really helpful. I almost got there, but it seems like if I map `mod4 + f` (left or right Super + "f") it only works for the right side Super key (`Super_R`) not the left side. `Super_L` seems locked to opening the applications in Ubuntu. I found this [work-around](https://askubuntu.com/questions/1071388/how-to-make-the-left-super-key-open-show-applications-menu-as-a-shortcut), but it seems like too much work :) 
```
$ xmodmap
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):
shift       Shift_L (0x32),  Shift_R (0x3e)
lock      
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

**Comment by e3rd** [comment]
I understand. However if you do not mind to change the opening shorcut, you may use `dconf-editor` and set another shortcut than `<Super>` in `panel-main-menu` (at `org/gnome/desktop/wm/keybindings`). My preferred combination is I.E.: `panel-main-menu=['<Ctrl>semicolon']`

Have a nice day!

**Comment by gitressa** [comment]
Thanks for the tip! What is strange, is that the definition for `panel-main-menu` was empty. I tried changing it to your suggestion, which worked fine. Yet, pressing the Left Super key still shows the activities overview ...

**Comment by e3rd** [comment]
You want to change or disable `org/gnome/mutter/overlay-key` :)

**Comment by gitressa** [comment]
That did it, thanks! I set `panel-main-menu` in `org/gnome/desktop/wm/keybindings` to `['<Ctrl>onehalf']`, since the `Esc` button used to close is just above.

**Comment by gitressa** [comment]
Update: I found a great solution using [xcape](https://github.com/alols/xcape), allowing me to have either Super key open the overlay: https://forum.xfce.org/viewtopic.php?pid=49054#p49054

For more:
- https://askubuntu.com/questions/1091877/assign-super-key-for-show-applications
- https://gitlab.xfce.org/xfce/libxfce4ui/-/issues/1
