### ISSUE TITLE
change behaviour?

### ISSUE THREAD

**Issue by gitlerat** [mkropat/jumpapp#65]
Hi is it possible to change the script that it creates the window firsttime and then minimize the window when it is already launched - and if it is launched but hidden, than rise the window?

kind regards

**Comment by gitlerat** [comment]
`#!/bin/bash



    # Get focused window
    focused_wid=$(xdotool getactivewindow)
# Get focused window class
    focused_wm_class=$(cat /proc/$(xdotool getwindowpid $(xdotool getwindowfocus))/comm)
    # And list of windows
    xdotool search --class . > /tmp/widids

    
if [[ "$focused_wm_class" == *"$1"* ]];
then
	# Check if the window is in the list (returns nothing if it's not)
	
   $focused_wid=$(awk -v var="$focused_wid" '$0 ~ var' /tmp/widids)
  $(xdotool windowminimize "$focused_wid")
   
else
$(wmctrl -xa "$1" || "$2")
fi`

**Comment by gitlerat** [comment]
The Aboce Code does following:

    launch the application if there is no instance open,

    if launched but not in focus it will focus it,

    if it is launched and focused it will minimize it


Sadly it is still not working on flatpaks because I am working with the process name and it seems that there is still a quirk

**Comment by mkropat** [comment]
Have you tried the `-m` option that was introduced in https://github.com/mkropat/jumpapp/pull/41 ? It sounds similar to what you are describing.
