### ISSUE TITLE
the man page should say Jumps to (focus) the "last" open window for an application

### ISSUE THREAD

**Issue by Muhammad-2021** [mkropat/jumpapp#68]
the man page say "Jumps to (focus) the first open window for an application" here it says "first",
but when i open different odt documents with libreoffice writer (for example open 1.odt then open 2.odt then open 3.odt) then run:
$ jumpapp libreoffice7.2
it activates the last opened document (3.odt) not the first opened one (1.odt)
so i think the man page should say "...last open window" not "...first open window"

**Comment by mkropat** [comment]
Yes, that's a good point. I can take a shot at fixing it.

**Comment by mkropat** [comment]
Thanks for the issue report! I took care of it in https://github.com/mkropat/jumpapp/pull/70 (Feedback welcome if anyone thinks further changes are warranted)

**Comment by Muhammad-2021** [comment]
thank you
